import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
interface Item { product_name:string;quantity:number;price:number; }
interface Payload { to:string;customer_name:string;order_id:string;total:number;items:Item[];cancel_token:string;origin:string; }
const fmt=(n:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(n);
serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  try{
    const p:Payload=await req.json();
    const KEY=Deno.env.get("RESEND_API_KEY");
    if(!KEY)return new Response(JSON.stringify({error:"RESEND_API_KEY not set"}),{status:500,headers:{...cors,"Content-Type":"application/json"}});
    const id=p.order_id.slice(0,8).toUpperCase();
    const cancelUrl=`${p.origin}/otkazi/${p.cancel_token}`;
    const rows=p.items.map(i=>`<tr><td style="padding:10px 16px;border-bottom:1px solid #222;font-size:14px;color:#ddd;">${i.product_name}</td><td style="padding:10px 16px;border-bottom:1px solid #222;text-align:center;color:#ddd;">${i.quantity}</td><td style="padding:10px 16px;border-bottom:1px solid #222;font-weight:700;color:#c9a227;text-align:right;">${fmt(i.price*i.quantity)}</td></tr>`).join("");
    const html=`<!DOCTYPE html><html><body style="margin:0;background:#0d0d0d;font-family:system-ui,sans-serif;"><div style="max-width:580px;margin:0 auto;padding:24px 16px;"><div style="background:#111;border:1px solid #1e1e1e;border-radius:20px;overflow:hidden;margin-bottom:20px;"><div style="height:4px;background:linear-gradient(90deg,#c9a227,#f0c040);"></div><div style="padding:32px;text-align:center;"><div style="font-size:30px;font-weight:900;letter-spacing:4px;color:#c9a227;">CAR-TECH RS</div></div></div><div style="background:#111;border:1px solid #1e2e1e;border-radius:20px;padding:32px;text-align:center;margin-bottom:20px;"><div style="font-size:56px;margin-bottom:16px;">✅</div><h1 style="margin:0;color:#fff;font-size:26px;font-weight:900;">Porudžbina Primljena!</h1><p style="color:#777;margin:10px 0 0;">Hvala na poverenju, <strong style="color:#c9a227;">${p.customer_name}</strong>!</p><div style="margin-top:20px;background:#0d0d0d;border-radius:12px;padding:12px 24px;display:inline-block;"><div style="color:#555;font-size:11px;text-transform:uppercase;letter-spacing:2px;">Broj porudžbine</div><div style="color:#c9a227;font-family:monospace;font-size:22px;font-weight:900;margin-top:4px;">#${id}</div></div></div><div style="background:#111;border:1px solid #1e1e1e;border-radius:20px;overflow:hidden;margin-bottom:20px;"><table style="width:100%;border-collapse:collapse;"><thead><tr style="background:#0d0d0d;"><th style="padding:10px 16px;font-size:11px;text-transform:uppercase;color:#444;text-align:left;">Proizvod</th><th style="padding:10px 16px;font-size:11px;color:#444;text-align:center;">Kom.</th><th style="padding:10px 16px;font-size:11px;color:#444;text-align:right;">Cena</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><td colspan="2" style="padding:16px;font-size:16px;font-weight:900;color:#fff;">UKUPNO</td><td style="padding:16px;font-size:22px;font-weight:900;color:#c9a227;text-align:right;">${fmt(p.total)}</td></tr></tfoot></table></div><div style="background:#110a0a;border:1px solid #2a1010;border-radius:20px;padding:24px;margin-bottom:20px;"><div style="color:#fff;font-weight:700;font-size:15px;margin-bottom:8px;">Promena planova?</div><div style="color:#888;font-size:13px;margin-bottom:16px;">Možete otkazati dok ne bude isporučena. Kliknite ispod:</div><a href="${cancelUrl}" style="display:inline-block;background:#b91c1c;color:#fff;text-decoration:none;padding:12px 24px;border-radius:12px;font-weight:700;">✕ Otkaži Porudžbinu</a></div><div style="text-align:center;color:#333;font-size:12px;"><div style="color:#c9a227;font-weight:700;font-size:14px;margin-bottom:4px;">CAR-TECH RS</div><div>info@car-tech.rs</div></div></div></body></html>`;
    const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:"Car-Tech RS <noreply@car-tech.rs>",to:[p.to],subject:`✅ Porudžbina #${id} potvrđena — Car-Tech RS`,html})});
    const data=await r.json();
    return new Response(JSON.stringify(data),{status:r.ok?200:400,headers:{...cors,"Content-Type":"application/json"}});
  }catch(e){return new Response(JSON.stringify({error:String(e)}),{status:500,headers:{...cors,"Content-Type":"application/json"}});}
});
