/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProizvodiRouteImport } from './routes/proizvodi'
import { Route as KorpaRouteImport } from './routes/korpa'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProizvodIdRouteImport } from './routes/proizvod.$id'
import { Route as OtkaziTokenRouteImport } from './routes/otkazi.$token'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminProizvodiRouteImport } from './routes/admin.proizvodi'
import { Route as AdminPorudzbineRouteImport } from './routes/admin.porudzbine'
import { Route as AdminKategorijeRouteImport } from './routes/admin.kategorije'
import { Route as AdminDodajRouteImport } from './routes/admin.dodaj'

const ProizvodiRoute = ProizvodiRouteImport.update({
  id: '/proizvodi',
  path: '/proizvodi',
  getParentRoute: () => rootRouteImport,
} as any)
const KorpaRoute = KorpaRouteImport.update({
  id: '/korpa',
  path: '/korpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProizvodIdRoute = ProizvodIdRouteImport.update({
  id: '/proizvod/$id',
  path: '/proizvod/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OtkaziTokenRoute = OtkaziTokenRouteImport.update({
  id: '/otkazi/$token',
  path: '/otkazi/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProizvodiRoute = AdminProizvodiRouteImport.update({
  id: '/proizvodi',
  path: '/proizvodi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPorudzbineRoute = AdminPorudzbineRouteImport.update({
  id: '/porudzbine',
  path: '/porudzbine',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKategorijeRoute = AdminKategorijeRouteImport.update({
  id: '/kategorije',
  path: '/kategorije',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDodajRoute = AdminDodajRouteImport.update({
  id: '/dodaj',
  path: '/dodaj',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/korpa': typeof KorpaRoute
  '/proizvodi': typeof ProizvodiRoute
  '/admin/dodaj': typeof AdminDodajRoute
  '/admin/kategorije': typeof AdminKategorijeRoute
  '/admin/porudzbine': typeof AdminPorudzbineRoute
  '/admin/proizvodi': typeof AdminProizvodiRoute
  '/admin/login': typeof AdminLoginRoute
  '/otkazi/$token': typeof OtkaziTokenRoute
  '/proizvod/$id': typeof ProizvodIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/korpa': typeof KorpaRoute
  '/proizvodi': typeof ProizvodiRoute
  '/admin/dodaj': typeof AdminDodajRoute
  '/admin/kategorije': typeof AdminKategorijeRoute
  '/admin/porudzbine': typeof AdminPorudzbineRoute
  '/admin/proizvodi': typeof AdminProizvodiRoute
  '/admin/login': typeof AdminLoginRoute
  '/otkazi/$token': typeof OtkaziTokenRoute
  '/proizvod/$id': typeof ProizvodIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/korpa': typeof KorpaRoute
  '/proizvodi': typeof ProizvodiRoute
  '/admin/dodaj': typeof AdminDodajRoute
  '/admin/kategorije': typeof AdminKategorijeRoute
  '/admin/porudzbine': typeof AdminPorudzbineRoute
  '/admin/proizvodi': typeof AdminProizvodiRoute
  '/admin_/login': typeof AdminLoginRoute
  '/otkazi/$token': typeof OtkaziTokenRoute
  '/proizvod/$id': typeof ProizvodIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/korpa'
    | '/proizvodi'
    | '/admin/dodaj'
    | '/admin/kategorije'
    | '/admin/porudzbine'
    | '/admin/proizvodi'
    | '/admin/login'
    | '/otkazi/$token'
    | '/proizvod/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/korpa'
    | '/proizvodi'
    | '/admin/dodaj'
    | '/admin/kategorije'
    | '/admin/porudzbine'
    | '/admin/proizvodi'
    | '/admin/login'
    | '/otkazi/$token'
    | '/proizvod/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/korpa'
    | '/proizvodi'
    | '/admin/dodaj'
    | '/admin/kategorije'
    | '/admin/porudzbine'
    | '/admin/proizvodi'
    | '/admin_/login'
    | '/otkazi/$token'
    | '/proizvod/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  KorpaRoute: typeof KorpaRoute
  ProizvodiRoute: typeof ProizvodiRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OtkaziTokenRoute: typeof OtkaziTokenRoute
  ProizvodIdRoute: typeof ProizvodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proizvodi': {
      id: '/proizvodi'
      path: '/proizvodi'
      fullPath: '/proizvodi'
      preLoaderRoute: typeof ProizvodiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korpa': {
      id: '/korpa'
      path: '/korpa'
      fullPath: '/korpa'
      preLoaderRoute: typeof KorpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/proizvod/$id': {
      id: '/proizvod/$id'
      path: '/proizvod/$id'
      fullPath: '/proizvod/$id'
      preLoaderRoute: typeof ProizvodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otkazi/$token': {
      id: '/otkazi/$token'
      path: '/otkazi/$token'
      fullPath: '/otkazi/$token'
      preLoaderRoute: typeof OtkaziTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proizvodi': {
      id: '/admin/proizvodi'
      path: '/proizvodi'
      fullPath: '/admin/proizvodi'
      preLoaderRoute: typeof AdminProizvodiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/porudzbine': {
      id: '/admin/porudzbine'
      path: '/porudzbine'
      fullPath: '/admin/porudzbine'
      preLoaderRoute: typeof AdminPorudzbineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kategorije': {
      id: '/admin/kategorije'
      path: '/kategorije'
      fullPath: '/admin/kategorije'
      preLoaderRoute: typeof AdminKategorijeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dodaj': {
      id: '/admin/dodaj'
      path: '/dodaj'
      fullPath: '/admin/dodaj'
      preLoaderRoute: typeof AdminDodajRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDodajRoute: typeof AdminDodajRoute
  AdminKategorijeRoute: typeof AdminKategorijeRoute
  AdminPorudzbineRoute: typeof AdminPorudzbineRoute
  AdminProizvodiRoute: typeof AdminProizvodiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDodajRoute: AdminDodajRoute,
  AdminKategorijeRoute: AdminKategorijeRoute,
  AdminPorudzbineRoute: AdminPorudzbineRoute,
  AdminProizvodiRoute: AdminProizvodiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  KorpaRoute: KorpaRoute,
  ProizvodiRoute: ProizvodiRoute,
  AdminLoginRoute: AdminLoginRoute,
  OtkaziTokenRoute: OtkaziTokenRoute,
  ProizvodIdRoute: ProizvodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
